/**
 * WorkstreamGenerator - Generates workstreams from strategic insights
 * 
 * Uses WBS Builder for semantic analysis and intelligent workstream generation.
 */

import type { StrategyInsights, StrategyInsight, UserContext, Workstream, Deliverable } from '../types';
import type { IWorkstreamGenerator } from '../../types/interfaces';
import { ContextBuilder } from './context-builder';
import { createWBSBuilder } from '../../../src/lib/intelligent-planning/wbs-builder';

export class WorkstreamGenerator implements IWorkstreamGenerator {
  private llm: any;

  constructor(llm?: any) {
    this.llm = llm;
  }

  /**
   * Generate workstreams using WBS Builder for semantic analysis
   */
  async generate(
    insights: StrategyInsights,
    userContext?: UserContext,
    onProgress?: (event: any) => void,
    startTime?: number
  ): Promise<Workstream[]> {
    console.log('\n' + '='.repeat(80));
    console.log('[WorkstreamGenerator] 📊 GENERATING WORKSTREAMS USING WBS BUILDER');
    console.log('='.repeat(80));
    
    const processStartTime = startTime || Date.now();
    
    try {
      console.log('[WorkstreamGenerator] Step 1: Building planning context from insights...');
      const planningContext = await ContextBuilder.fromJourneyInsights(
        insights,
        insights.frameworkType || 'strategy_workspace',
        userContext?.sessionId
      );
      
      console.log('[WorkstreamGenerator] ✓ Planning Context Created:');
      console.log(`  Business Name: "${planningContext.business.name}"`);
      console.log(`  Business Type: ${planningContext.business.type}`);
      console.log(`  Business Scale: ${planningContext.business.scale}`);
      console.log(`  Timeline Range: ${planningContext.execution.timeline.min}-${planningContext.execution.timeline.max} months`);
      console.log(`  Budget Range: $${planningContext.execution.budget?.min || 'N/A'} - $${planningContext.execution.budget?.max || 'N/A'}`);
      console.log(`  Total Insights: ${insights.insights.length}`);
      console.log(`  Framework Type: ${insights.frameworkType}`);
      
      console.log('\n[WorkstreamGenerator] Step 2: Creating WBS Builder with LLM provider...');
      const wbsBuilder = createWBSBuilder(this.llm, (current, total, workstreamName) => {
        if (onProgress) {
          const elapsedSeconds = Math.round((Date.now() - processStartTime) / 1000);
          onProgress({
            type: 'step-start',
            step: 'wbs-generation',
            progress: Math.round((current / total) * 100),
            description: `Generating workstream ${current}/${total}: ${workstreamName}`,
            elapsedSeconds
          });
        }
      });
      console.log('[WorkstreamGenerator] ✓ WBS Builder created');
      
      console.log('\n[WorkstreamGenerator] Step 3: Calling WBS Builder to generate workstreams...');
      console.log('[WorkstreamGenerator] >>> Passing to WBS Builder:');
      console.log(`  - Insights count: ${insights.insights.length}`);
      console.log(`  - Planning context: Business=${planningContext.business.name}, Scale=${planningContext.business.scale}`);
      
      const wbs = await wbsBuilder.buildWBS(insights, planningContext);
      
      console.log('\n[WorkstreamGenerator] ✓ WBS Builder Completed Successfully!');
      console.log('[WorkstreamGenerator] 📋 WBS BUILDER RESULTS:');
      console.log('─'.repeat(80));
      console.log(`  Initiative Type: ${wbs.intent.initiativeType}`);
      console.log(`  Technology Role: ${wbs.intent.technologyRole}`);
      console.log(`  Total Workstreams: ${wbs.workstreams.length}`);
      console.log(`  Validation Status: ${wbs.validationReport.isValid ? '✓ PASSED' : '✗ FAILED'}`);
      console.log(`  Coherence Score: ${(wbs.validationReport.coherenceScore * 100).toFixed(1)}%`);
      console.log(`  Confidence: ${(wbs.intent.confidence * 100).toFixed(1)}%`);
      
      console.log('\n[WorkstreamGenerator] 📦 WORKSTREAMS GENERATED BY WBS:');
      wbs.workstreams.forEach((ws, idx) => {
        console.log(`\n  Workstream ${idx + 1}: ${ws.name} (${ws.id})`);
        console.log(`    Description: ${ws.description.substring(0, 100)}...`);
        console.log(`    Deliverables: ${ws.deliverables.length}`);
        ws.deliverables.forEach((d, di) => {
          const delivName = typeof d === 'string' ? d : (d as any).name || 'Unknown';
          console.log(`      ${di + 1}. ${delivName}`);
        });
        console.log(`    Dependencies: ${ws.dependencies.length > 0 ? ws.dependencies.join(', ') : 'None'}`);
        console.log(`    Confidence: ${(ws.confidence * 100).toFixed(1)}%`);
      });
      
      console.log('\n[WorkstreamGenerator] Step 4: Converting WBS workstreams to EPM format...');
      const workstreams: Workstream[] = wbs.workstreams.map((ws, index) => {
        const deliverables: Deliverable[] = ws.deliverables.map((delivName, delIndex) => ({
          id: `${ws.id}-D${delIndex + 1}`,
          name: delivName,
          description: delivName,
          dueMonth: 0,
          effort: '1 person-month',
        }));
        
        return {
          id: ws.id,
          name: ws.name,
          description: ws.description,
          deliverables,
          startMonth: 0,
          endMonth: 0,
          dependencies: ws.dependencies,
          confidence: ws.confidence,
        };
      });
      
      if (workstreams.length < 3) {
        console.warn('[WorkstreamGenerator] WBS generated less than 3 workstreams, adding defaults');
        workstreams.push(...this.generateDefaultWorkstreams(3 - workstreams.length));
      }
      
      console.log(`\n[WorkstreamGenerator] ✓ Successfully converted ${workstreams.length} workstreams to EPM format`);
      console.log('[WorkstreamGenerator] 📊 EPM WORKSTREAMS READY FOR INTELLIGENT PLANNING:');
      workstreams.forEach((ws, idx) => {
        console.log(`  ${idx + 1}. ${ws.name} (${ws.id})`);
        console.log(`     - Deliverables: ${ws.deliverables.length}`);
        console.log(`     - Dependencies: ${ws.dependencies.length > 0 ? ws.dependencies.join(', ') : 'None'}`);
      });
      console.log('='.repeat(80) + '\n');
      
      return workstreams;
      
    } catch (error) {
      console.error('[WorkstreamGenerator] WBS Builder failed, falling back to legacy generation:', error);
      
      const workstreamInsights = insights.insights.filter(i => i.type === 'workstream');
      
      const workstreams: Workstream[] = workstreamInsights.map((insight, index) => {
        const deliverables = this.generateDeliverables(insight, index);
        
        return {
          id: `WS${String(index + 1).padStart(3, '0')}`,
          name: insight.content.split('\n')[0] || `Workstream ${index + 1}`,
          description: insight.content,
          deliverables,
          startMonth: Math.floor(index / 2) + 1,
          endMonth: Math.min(Math.floor(index / 2) + 1 + deliverables.length, 12),
          dependencies: index > 0 ? [`WS${String(index).padStart(3, '0')}`] : [],
          confidence: insight.confidence,
        };
      });

      if (workstreams.length < 3) {
        workstreams.push(...this.generateDefaultWorkstreams(3 - workstreams.length));
      }

      return workstreams;
    }
  }

  /**
   * Generate deliverables from insight
   */
  generateDeliverables(insight: StrategyInsight, workstreamIndex: number): Deliverable[] {
    const lines = insight.content.split('\n').filter(l => l.trim());
    const deliverableLines = lines.slice(1, 4);
    
    return deliverableLines.map((line, idx) => ({
      id: `D${String(workstreamIndex + 1).padStart(3, '0')}.${idx + 1}`,
      name: line.replace(/^[-•]\s*/, '').trim(),
      description: line.replace(/^[-•]\s*/, '').trim(),
      dueMonth: workstreamIndex + idx + 2,
      effort: this.estimateEffort(line),
    }));
  }

  /**
   * Generate default workstreams
   */
  generateDefaultWorkstreams(count: number): Workstream[] {
    const defaults = [
      { name: 'Program Management', description: 'Overall program coordination, governance, and stakeholder management' },
      { name: 'Change Management', description: 'Organizational change, training, and adoption support' },
      { name: 'Quality Assurance', description: 'Quality reviews, testing, and validation' },
    ];

    return defaults.slice(0, count).map((def, idx) => ({
      id: `WS${String(idx + 100).padStart(3, '0')}`,
      name: def.name,
      description: def.description,
      deliverables: [],
      startMonth: 1,
      endMonth: 12,
      dependencies: [],
      confidence: 0.70,
    }));
  }

  /**
   * Estimate effort for a deliverable
   */
  estimateEffort(deliverable: string): string {
    const words = deliverable.split(' ').length;
    if (words < 5) return '5-10 person-days';
    if (words < 10) return '10-20 person-days';
    return '20-40 person-days';
  }
}

export default WorkstreamGenerator;
