// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/sync-journeys.ts

import type { JourneyType } from '../shared/journey-types';

/**
 * All registered journey types.
 * Update server/journey/journey-registry.ts to add new journeys.
 */
export const REGISTERED_JOURNEY_TYPES = [
  'business_model_innovation',
  'market_entry',
  'competitive_strategy',
  'digital_transformation',
  'crisis_recovery',
  'growth_strategy',
] as const;

export type RegisteredJourneyType = typeof REGISTERED_JOURNEY_TYPES[number];

/**
 * Validates that a journey type is registered.
 */
export function isRegisteredJourneyType(type: string): type is RegisteredJourneyType {
  return REGISTERED_JOURNEY_TYPES.includes(type as RegisteredJourneyType);
}
